
platform :ios, '8.0'
inhibit_all_warnings!

target 'Native_oc' do
pod 'AFNetworking'
pod 'YYKit'
pod 'Masonry'
end


flutter_application_path = "../flutter_module"
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
