

platform :ios, '9.0'
use_frameworks!


flutter_application_path = './flutter_module'
  eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)


target 'Native-iOS' do
pod 'AFNetworking', '~> 2.6'
end
